#include "instructions/x64instruction.h"
#include "instructions/instructionutils.h"

namespace x64 {

    
    static inline std::string toString([[maybe_unused]] const X64Instruction& insn, const char* mnemonic) {
        assert(insn.nbOperands() == 0);
        return fmt::format("{:9}", mnemonic);
    }

    template<typename T0>
    static inline std::string toString(const X64Instruction& insn, const char* mnemonic) {
        return fmt::format("{:9}{}", mnemonic, utils::toString(insn.op0<T0>()));
    }

    template<typename T0, typename T1>
    static inline std::string toString(const X64Instruction& insn, const char* mnemonic) {
        return fmt::format("{:9}{},{}", mnemonic, utils::toString(insn.op0<T0>()), utils::toString(insn.op1<T1>()));
    }

    template<typename T0, typename T1, typename T2>
    static inline std::string toString(const X64Instruction& insn, const char* mnemonic) {
        return fmt::format("{:9}{},{},{}", mnemonic, utils::toString(insn.op0<T0>()), utils::toString(insn.op1<T1>()), utils::toString(insn.op2<T2>()));
    }

    std::string X64Instruction::toString() const {
        switch(insn()) {
            case Insn::ADD_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "add");
            case Insn::ADD_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "add");
            case Insn::ADD_RM16_RM16: return x64::toString<RM16, RM16>(*this, "add");
            case Insn::ADD_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "add");
            case Insn::ADD_RM32_RM32: return x64::toString<RM32, RM32>(*this, "add");
            case Insn::ADD_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "add");
            case Insn::ADD_RM64_RM64: return x64::toString<RM64, RM64>(*this, "add");
            case Insn::ADD_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "add");
            case Insn::ADC_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "adc");
            case Insn::ADC_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "adc");
            case Insn::ADC_RM16_RM16: return x64::toString<RM16, RM16>(*this, "adc");
            case Insn::ADC_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "adc");
            case Insn::ADC_RM32_RM32: return x64::toString<RM32, RM32>(*this, "adc");
            case Insn::ADC_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "adc");
            case Insn::ADC_RM64_RM64: return x64::toString<RM64, RM64>(*this, "adc");
            case Insn::ADC_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "adc");
            case Insn::SUB_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "sub");
            case Insn::SUB_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "sub");
            case Insn::SUB_RM16_RM16: return x64::toString<RM16, RM16>(*this, "sub");
            case Insn::SUB_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "sub");
            case Insn::SUB_RM32_RM32: return x64::toString<RM32, RM32>(*this, "sub");
            case Insn::SUB_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "sub");
            case Insn::SUB_RM64_RM64: return x64::toString<RM64, RM64>(*this, "sub");
            case Insn::SUB_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "sub");
            case Insn::SBB_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "sbb");
            case Insn::SBB_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "sbb");
            case Insn::SBB_RM16_RM16: return x64::toString<RM16, RM16>(*this, "sbb");
            case Insn::SBB_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "sbb");
            case Insn::SBB_RM32_RM32: return x64::toString<RM32, RM32>(*this, "sbb");
            case Insn::SBB_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "sbb");
            case Insn::SBB_RM64_RM64: return x64::toString<RM64, RM64>(*this, "sbb");
            case Insn::SBB_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "sbb");
            case Insn::NEG_RM8:  return x64::toString<RM8>(*this, "neg");
            case Insn::NEG_RM16: return x64::toString<RM16>(*this, "neg");
            case Insn::NEG_RM32: return x64::toString<RM32>(*this, "neg");
            case Insn::NEG_RM64: return x64::toString<RM64>(*this, "neg");
            case Insn::MUL_RM32: return x64::toString<RM32>(*this, "mul");
            case Insn::MUL_RM64: return x64::toString<RM64>(*this, "mul");
            case Insn::IMUL1_RM32: return x64::toString<RM32>(*this, "imul");
            case Insn::IMUL2_R32_RM32: return x64::toString<R32, RM32>(*this, "imul");
            case Insn::IMUL3_R32_RM32_IMM: return x64::toString<R32, RM32, Imm>(*this, "imul");
            case Insn::IMUL1_RM64: return x64::toString<RM64>(*this, "imul");
            case Insn::IMUL2_R64_RM64: return x64::toString<R64, RM64>(*this, "imul");
            case Insn::IMUL3_R64_RM64_IMM: return x64::toString<R64, RM64, Imm>(*this, "imul");
            case Insn::DIV_RM32: return x64::toString<RM32>(*this, "div");
            case Insn::DIV_RM64: return x64::toString<RM64>(*this, "div");
            case Insn::IDIV_RM32: return x64::toString<RM32>(*this, "idiv");
            case Insn::IDIV_RM64: return x64::toString<RM64>(*this, "idiv");
            case Insn::AND_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "and");
            case Insn::AND_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "and");
            case Insn::AND_RM16_RM16: return x64::toString<RM16, RM16>(*this, "and");
            case Insn::AND_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "and");
            case Insn::AND_RM32_RM32: return x64::toString<RM32, RM32>(*this, "and");
            case Insn::AND_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "and");
            case Insn::AND_RM64_RM64: return x64::toString<RM64, RM64>(*this, "and");
            case Insn::AND_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "and");
            case Insn::OR_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "or");
            case Insn::OR_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "or");
            case Insn::OR_RM16_RM16: return x64::toString<RM16, RM16>(*this, "or");
            case Insn::OR_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "or");
            case Insn::OR_RM32_RM32: return x64::toString<RM32, RM32>(*this, "or");
            case Insn::OR_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "or");
            case Insn::OR_RM64_RM64: return x64::toString<RM64, RM64>(*this, "or");
            case Insn::OR_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "or");
            case Insn::XOR_RM8_RM8:   return x64::toString<RM8, RM8>(*this, "xor");
            case Insn::XOR_RM8_IMM:   return x64::toString<RM8, Imm>(*this, "xor");
            case Insn::XOR_RM16_RM16: return x64::toString<RM16, RM16>(*this, "xor");
            case Insn::XOR_RM16_IMM:  return x64::toString<RM16, Imm>(*this, "xor");
            case Insn::XOR_RM32_RM32: return x64::toString<RM32, RM32>(*this, "xor");
            case Insn::XOR_RM32_IMM:  return x64::toString<RM32, Imm>(*this, "xor");
            case Insn::XOR_RM64_RM64: return x64::toString<RM64, RM64>(*this, "xor");
            case Insn::XOR_RM64_IMM:  return x64::toString<RM64, Imm>(*this, "xor");
            case Insn::NOT_RM8:  return x64::toString<RM8>(*this, "not");
            case Insn::NOT_RM16: return x64::toString<RM16>(*this, "not");
            case Insn::NOT_RM32: return x64::toString<RM32>(*this, "not");
            case Insn::NOT_RM64: return x64::toString<RM64>(*this, "not");
            case Insn::XCHG_RM16_R16: return x64::toString<RM16, R16>(*this, "xchg");
            case Insn::XCHG_RM32_R32: return x64::toString<RM32, R32>(*this, "xchg");
            case Insn::XCHG_RM64_R64: return x64::toString<RM64, R64>(*this, "xchg");
            case Insn::XADD_RM16_R16: return x64::toString<RM16, R16>(*this, "xadd");
            case Insn::XADD_RM32_R32: return x64::toString<RM32, R32>(*this, "xadd");
            case Insn::XADD_RM64_R64: return x64::toString<RM64, R64>(*this, "xadd");
            case Insn::MOV_RM8_RM8:     return x64::toString<RM8, RM8>(*this, "mov");
            case Insn::MOV_RM8_IMM:     return x64::toString<RM8, Imm>(*this, "mov");
            case Insn::MOV_RM16_RM16:   return x64::toString<RM16, RM16>(*this, "mov");
            case Insn::MOV_RM16_IMM:    return x64::toString<RM16, Imm>(*this, "mov");
            case Insn::MOV_RM32_RM32:   return x64::toString<RM32, RM32>(*this, "mov");
            case Insn::MOV_RM32_IMM:    return x64::toString<RM32, Imm>(*this, "mov");
            case Insn::MOV_RM64_RM64:   return x64::toString<RM64, RM64>(*this, "mov");
            case Insn::MOV_RM64_IMM:    return x64::toString<RM64, Imm>(*this, "mov");
            case Insn::MOV_RMSSE_RMSSE: return x64::toString<RMSSE, RMSSE>(*this, "mov");
            case Insn::MOVSX_R16_RM8:  return x64::toString<R16, RM8>(*this, "movsx");
            case Insn::MOVSX_R32_RM8:  return x64::toString<R32, RM8>(*this, "movsx");
            case Insn::MOVSX_R32_RM16: return x64::toString<R32, RM16>(*this, "movsx");
            case Insn::MOVSX_R64_RM8:  return x64::toString<R64, RM8>(*this, "movsx");
            case Insn::MOVSX_R64_RM16: return x64::toString<R64, RM16>(*this, "movsx");
            case Insn::MOVSX_R64_RM32: return x64::toString<R64, RM32>(*this, "movsx");
            case Insn::MOVZX_R16_RM8:  return x64::toString<R16, RM8>(*this, "movzx");
            case Insn::MOVZX_R32_RM8:  return x64::toString<R32, RM8>(*this, "movzx");
            case Insn::MOVZX_R32_RM16: return x64::toString<R32, RM16>(*this, "movzx");
            case Insn::MOVZX_R64_RM8:  return x64::toString<R64, RM8>(*this, "movzx");
            case Insn::MOVZX_R64_RM16: return x64::toString<R64, RM16>(*this, "movzx");
            case Insn::MOVZX_R64_RM32: return x64::toString<R64, RM32>(*this, "movzx");
            case Insn::LEA_R32_ENCODING: return x64::toString<R32, Encoding>(*this, "lea");
            case Insn::LEA_R64_ENCODING: return x64::toString<R64, Encoding>(*this, "lea");
            case Insn::PUSH_IMM: return x64::toString<Imm>(*this, "push");
            case Insn::PUSH_RM32: return x64::toString<RM32>(*this, "push");
            case Insn::PUSH_RM64: return x64::toString<RM64>(*this, "push");
            case Insn::POP_R32: return x64::toString<R32>(*this, "pop");
            case Insn::POP_R64: return x64::toString<R64>(*this, "pop");
            case Insn::CALLDIRECT: return x64::toString<u64>(*this, "call");
            case Insn::CALLINDIRECT_RM32: return x64::toString<RM32>(*this, "call");
            case Insn::CALLINDIRECT_RM64: return x64::toString<RM64>(*this, "call");
            case Insn::RET: return x64::toString(*this, "ret");
            case Insn::RET_IMM: return x64::toString<Imm>(*this, "ret");
            case Insn::LEAVE: return x64::toString(*this, "leave");
            case Insn::HALT: return x64::toString(*this, "halt");
            case Insn::NOP: return x64::toString(*this, "nop");
            case Insn::UD2: return x64::toString(*this, "ud2");
            case Insn::SYSCALL: return x64::toString(*this, "syscall");
            case Insn::UNKNOWN: return x64::toString<std::array<char, 16>>(*this, "unkn");
            case Insn::CDQ: return x64::toString(*this, "cdq");
            case Insn::CQO: return x64::toString(*this, "cqo");
            case Insn::INC_RM8: return x64::toString<RM8>(*this, "inc");
            case Insn::INC_RM16: return x64::toString<RM16>(*this, "inc");
            case Insn::INC_RM32: return x64::toString<RM32>(*this, "inc");
            case Insn::INC_RM64: return x64::toString<RM64>(*this, "inc");
            case Insn::DEC_RM8: return x64::toString<RM8>(*this, "dec");
            case Insn::DEC_RM16: return x64::toString<RM16>(*this, "dec");
            case Insn::DEC_RM32: return x64::toString<RM32>(*this, "dec");
            case Insn::DEC_RM64: return x64::toString<RM64>(*this, "dec");
            case Insn::SHR_RM8_R8: return x64::toString<RM8, R8>(*this, "shr");
            case Insn::SHR_RM8_IMM: return x64::toString<RM8, Imm>(*this, "shr");
            case Insn::SHR_RM16_R8: return x64::toString<RM16, R8>(*this, "shr");
            case Insn::SHR_RM16_IMM: return x64::toString<RM16, Imm>(*this, "shr");
            case Insn::SHR_RM32_R8: return x64::toString<RM32, R8>(*this, "shr");
            case Insn::SHR_RM32_IMM: return x64::toString<RM32, Imm>(*this, "shr");
            case Insn::SHR_RM64_R8: return x64::toString<RM64, R8>(*this, "shr");
            case Insn::SHR_RM64_IMM: return x64::toString<RM64, Imm>(*this, "shr");
            case Insn::SHL_RM8_R8: return x64::toString<RM8, R8>(*this, "shl");
            case Insn::SHL_RM8_IMM: return x64::toString<RM8, Imm>(*this, "shl");
            case Insn::SHL_RM16_R8: return x64::toString<RM16, R8>(*this, "shl");
            case Insn::SHL_RM16_IMM: return x64::toString<RM16, Imm>(*this, "shl");
            case Insn::SHL_RM32_R8: return x64::toString<RM32, R8>(*this, "shl");
            case Insn::SHL_RM32_IMM: return x64::toString<RM32, Imm>(*this, "shl");
            case Insn::SHL_RM64_R8: return x64::toString<RM64, R8>(*this, "shl");
            case Insn::SHL_RM64_IMM: return x64::toString<RM64, Imm>(*this, "shl");
            case Insn::SHLD_RM32_R32_R8: return x64::toString<RM32, R32, R8>(*this, "shld");
            case Insn::SHLD_RM32_R32_IMM: return x64::toString<RM32, R32, Imm>(*this, "shld");
            case Insn::SHLD_RM64_R64_R8: return x64::toString<RM64, R64, R8>(*this, "shld");
            case Insn::SHLD_RM64_R64_IMM: return x64::toString<RM64, R64, Imm>(*this, "shld");
            case Insn::SHRD_RM32_R32_R8: return x64::toString<RM32, R32, R8>(*this, "shrd");
            case Insn::SHRD_RM32_R32_IMM: return x64::toString<RM32, R32, Imm>(*this, "shrd");
            case Insn::SHRD_RM64_R64_R8: return x64::toString<RM64, R64, R8>(*this, "shrd");
            case Insn::SHRD_RM64_R64_IMM: return x64::toString<RM64, R64, Imm>(*this, "shrd");
            case Insn::SAR_RM8_R8: return x64::toString<RM8, R8>(*this, "sar");
            case Insn::SAR_RM8_IMM: return x64::toString<RM8, Imm>(*this, "sar");
            case Insn::SAR_RM16_R8: return x64::toString<RM16, R8>(*this, "sar");
            case Insn::SAR_RM16_IMM: return x64::toString<RM16, Imm>(*this, "sar");
            case Insn::SAR_RM32_R8: return x64::toString<RM32, R8>(*this, "sar");
            case Insn::SAR_RM32_IMM: return x64::toString<RM32, Imm>(*this, "sar");
            case Insn::SAR_RM64_R8: return x64::toString<RM64, R8>(*this, "sar");
            case Insn::SAR_RM64_IMM: return x64::toString<RM64, Imm>(*this, "sar");
            case Insn::ROL_RM8_R8: return x64::toString<RM8, R8>(*this, "rol");
            case Insn::ROL_RM8_IMM: return x64::toString<RM8, Imm>(*this, "rol");
            case Insn::ROL_RM16_R8: return x64::toString<RM16, R8>(*this, "rol");
            case Insn::ROL_RM16_IMM: return x64::toString<RM16, Imm>(*this, "rol");
            case Insn::ROL_RM32_R8: return x64::toString<RM32, R8>(*this, "rol");
            case Insn::ROL_RM32_IMM: return x64::toString<RM32, Imm>(*this, "rol");
            case Insn::ROL_RM64_R8: return x64::toString<RM64, R8>(*this, "rol");
            case Insn::ROL_RM64_IMM: return x64::toString<RM64, Imm>(*this, "rol");
            case Insn::ROR_RM8_R8: return x64::toString<RM8, R8>(*this, "ror");
            case Insn::ROR_RM8_IMM: return x64::toString<RM8, Imm>(*this, "ror");
            case Insn::ROR_RM16_R8: return x64::toString<RM16, R8>(*this, "ror");
            case Insn::ROR_RM16_IMM: return x64::toString<RM16, Imm>(*this, "ror");
            case Insn::ROR_RM32_R8: return x64::toString<RM32, R8>(*this, "ror");
            case Insn::ROR_RM32_IMM: return x64::toString<RM32, Imm>(*this, "ror");
            case Insn::ROR_RM64_R8: return x64::toString<RM64, R8>(*this, "ror");
            case Insn::ROR_RM64_IMM: return x64::toString<RM64, Imm>(*this, "ror");
            case Insn::TZCNT_R16_RM16: return x64::toString<R16, RM16>(*this, "tzcnt");
            case Insn::TZCNT_R32_RM32: return x64::toString<R32, RM32>(*this, "tzcnt");
            case Insn::TZCNT_R64_RM64: return x64::toString<R64, RM64>(*this, "tzcnt");
            case Insn::BT_RM16_R16: return x64::toString<RM16, R16>(*this, "bt");
            case Insn::BT_RM16_IMM: return x64::toString<RM16, Imm>(*this, "bt");
            case Insn::BT_RM32_R32: return x64::toString<RM32, R32>(*this, "bt");
            case Insn::BT_RM32_IMM: return x64::toString<RM32, Imm>(*this, "bt");
            case Insn::BT_RM64_R64: return x64::toString<RM64, R64>(*this, "bt");
            case Insn::BT_RM64_IMM: return x64::toString<RM64, Imm>(*this, "bt");
            case Insn::BTR_RM16_R16: return x64::toString<RM16, R16>(*this, "btr");
            case Insn::BTR_RM16_IMM: return x64::toString<RM16, Imm>(*this, "btr");
            case Insn::BTR_RM32_R32: return x64::toString<RM32, R32>(*this, "btr");
            case Insn::BTR_RM32_IMM: return x64::toString<RM32, Imm>(*this, "btr");
            case Insn::BTR_RM64_R64: return x64::toString<RM64, R64>(*this, "btr");
            case Insn::BTR_RM64_IMM: return x64::toString<RM64, Imm>(*this, "btr");
            case Insn::BTC_RM16_R16: return x64::toString<RM16, R16>(*this, "btc");
            case Insn::BTC_RM16_IMM: return x64::toString<RM16, Imm>(*this, "btc");
            case Insn::BTC_RM32_R32: return x64::toString<RM32, R32>(*this, "btc");
            case Insn::BTC_RM32_IMM: return x64::toString<RM32, Imm>(*this, "btc");
            case Insn::BTC_RM64_R64: return x64::toString<RM64, R64>(*this, "btc");
            case Insn::BTC_RM64_IMM: return x64::toString<RM64, Imm>(*this, "btc");
            case Insn::BTS_RM16_R16: return x64::toString<RM16, R16>(*this, "bts");
            case Insn::BTS_RM16_IMM: return x64::toString<RM16, Imm>(*this, "bts");
            case Insn::BTS_RM32_R32: return x64::toString<RM32, R32>(*this, "bts");
            case Insn::BTS_RM32_IMM: return x64::toString<RM32, Imm>(*this, "bts");
            case Insn::BTS_RM64_R64: return x64::toString<RM64, R64>(*this, "bts");
            case Insn::BTS_RM64_IMM: return x64::toString<RM64, Imm>(*this, "bts");
            case Insn::TEST_RM8_R8: return x64::toString<RM8, R8>(*this, "test");
            case Insn::TEST_RM8_IMM: return x64::toString<RM8, Imm>(*this, "test");
            case Insn::TEST_RM16_R16: return x64::toString<RM16, R16>(*this, "test");
            case Insn::TEST_RM16_IMM: return x64::toString<RM16, Imm>(*this, "test");
            case Insn::TEST_RM32_R32: return x64::toString<RM32, R32>(*this, "test");
            case Insn::TEST_RM32_IMM: return x64::toString<RM32, Imm>(*this, "test");
            case Insn::TEST_RM64_R64: return x64::toString<RM64, R64>(*this, "test");
            case Insn::TEST_RM64_IMM: return x64::toString<RM64, Imm>(*this, "test");
            case Insn::CMP_RM8_RM8: return x64::toString<RM8, RM8>(*this, "cmp");
            case Insn::CMP_RM8_IMM: return x64::toString<RM8, Imm>(*this, "cmp");
            case Insn::CMP_RM16_RM16: return x64::toString<RM16, RM16>(*this, "cmp");
            case Insn::CMP_RM16_IMM: return x64::toString<RM16, Imm>(*this, "cmp");
            case Insn::CMP_RM32_RM32: return x64::toString<RM32, RM32>(*this, "cmp");
            case Insn::CMP_RM32_IMM: return x64::toString<RM32, Imm>(*this, "cmp");
            case Insn::CMP_RM64_RM64: return x64::toString<RM64, RM64>(*this, "cmp");
            case Insn::CMP_RM64_IMM: return x64::toString<RM64, Imm>(*this, "cmp");
            case Insn::CMPXCHG_RM8_R8: return x64::toString<RM8, R8>(*this, "cmpxchg");
            case Insn::CMPXCHG_RM16_R16: return x64::toString<RM16, R16>(*this, "cmpxchg");
            case Insn::CMPXCHG_RM32_R32: return x64::toString<RM32, R32>(*this, "cmpxchg");
            case Insn::CMPXCHG_RM64_R64: return x64::toString<RM64, R64>(*this, "cmpxchg");
            case Insn::SET_RM8: return x64::toString<Cond, RM8>(*this, "set");
            case Insn::JMP_RM32: return x64::toString<RM32>(*this, "jmp");
            case Insn::JMP_RM64: return x64::toString<RM64>(*this, "jmp");
            case Insn::JMP_U32: return x64::toString<u32>(*this, "jmp");
            case Insn::JCC: return x64::toString<Cond, u64>(*this, "jcc");
            case Insn::BSR_R32_R32: return x64::toString<R32, R32>(*this, "bsr");
            case Insn::BSR_R64_R64: return x64::toString<R64, R64>(*this, "bsr");
            case Insn::BSF_R32_R32: return x64::toString<R32, R32>(*this, "bsf");
            case Insn::BSF_R64_R64: return x64::toString<R64, R64>(*this, "bsf");
            case Insn::CLD: return x64::toString(*this, "cld");
            case Insn::STD: return x64::toString(*this, "std");
            case Insn::MOVS_M64_M64: return x64::toString<M64, M64>(*this, "movs");
            case Insn::REP_MOVS_M8_M8: return x64::toString<M8, M8>(*this, "rep movs");
            case Insn::REP_MOVS_M32_M32: return x64::toString<M32, M32>(*this, "rep movs");
            case Insn::REP_MOVS_M64_M64: return x64::toString<M64, M64>(*this, "rep movs");
            case Insn::REP_CMPS_M8_M8: return x64::toString<M8, M8>(*this, "rep cmps");
            case Insn::REP_STOS_M8_R8: return x64::toString<M8, R8>(*this, "rep stos");
            case Insn::REP_STOS_M16_R16: return x64::toString<M16, R16>(*this, "rep stos");
            case Insn::REP_STOS_M32_R32: return x64::toString<M32, R32>(*this, "rep stos");
            case Insn::REP_STOS_M64_R64: return x64::toString<M64, R64>(*this, "rep stos");
            case Insn::REPNZ_SCAS_R8_M8: return x64::toString<R8, M8>(*this, "repnz scas");
            case Insn::CMOV_R16_RM16: return x64::toString<Cond, R16, RM16>(*this, "cmov");
            case Insn::CMOV_R32_RM32: return x64::toString<Cond, R32, RM32>(*this, "cmov");
            case Insn::CMOV_R64_RM64: return x64::toString<Cond, R64, RM64>(*this, "cmov");
            case Insn::CWDE: return x64::toString(*this, "cwde");
            case Insn::CDQE: return x64::toString(*this, "cdqe");
            case Insn::BSWAP_R32: return x64::toString<R32>(*this, "bswap");
            case Insn::BSWAP_R64: return x64::toString<R64>(*this, "bswap");
            case Insn::PXOR_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pxor");
            case Insn::MOVAPS_RMSSE_RMSSE: return x64::toString<RMSSE, RMSSE>(*this, "movaps");
            case Insn::MOVD_RSSE_RM32: return x64::toString<RSSE, RM32>(*this, "movd");
            case Insn::MOVD_RM32_RSSE: return x64::toString<RM32, RSSE>(*this, "movd");
            case Insn::MOVD_RSSE_RM64: return x64::toString<RSSE, RM64>(*this, "movd");
            case Insn::MOVD_RM64_RSSE: return x64::toString<RM64, RSSE>(*this, "movd");
            case Insn::MOVQ_RSSE_RM64: return x64::toString<RSSE, RM64>(*this, "movq");
            case Insn::MOVQ_RM64_RSSE: return x64::toString<RM64, RSSE>(*this, "movq");
            case Insn::FLDZ: return x64::toString(*this, "fldz");
            case Insn::FLD1: return x64::toString(*this, "fld1");
            case Insn::FLD_ST: return x64::toString<ST>(*this, "fld");
            case Insn::FLD_M32: return x64::toString<M32>(*this, "fld");
            case Insn::FLD_M64: return x64::toString<M64>(*this, "fld");
            case Insn::FLD_M80: return x64::toString<M80>(*this, "fld");
            case Insn::FILD_M16: return x64::toString<M16>(*this, "fild");
            case Insn::FILD_M32: return x64::toString<M32>(*this, "fild");
            case Insn::FILD_M64: return x64::toString<M64>(*this, "fild");
            case Insn::FSTP_ST: return x64::toString<ST>(*this, "fstp");
            case Insn::FSTP_M32: return x64::toString<M32>(*this, "fstp");
            case Insn::FSTP_M64: return x64::toString<M64>(*this, "fstp");
            case Insn::FSTP_M80: return x64::toString<M80>(*this, "fstp");
            case Insn::FISTP_M16: return x64::toString<M16>(*this, "fistp");
            case Insn::FISTP_M32: return x64::toString<M32>(*this, "fistp");
            case Insn::FISTP_M64: return x64::toString<M64>(*this, "fistp");
            case Insn::FXCH_ST: return x64::toString<ST>(*this, "fxch");
            case Insn::FADDP_ST: return x64::toString<ST>(*this, "faddp");
            case Insn::FSUBRP_ST: return x64::toString<ST>(*this, "fsubrp");
            case Insn::FMUL1_M32: return x64::toString<M32>(*this, "fmul1");
            case Insn::FMUL1_M64: return x64::toString<M64>(*this, "fmul1");
            case Insn::FDIV_ST_ST: return x64::toString<ST, ST>(*this, "fdiv");
            case Insn::FDIVP_ST_ST: return x64::toString<ST, ST>(*this, "fdivp");
            case Insn::FCOMI_ST: return x64::toString<ST>(*this, "fcomi");
            case Insn::FUCOMI_ST: return x64::toString<ST>(*this, "fucomi");
            case Insn::FRNDINT: return x64::toString(*this, "frndint");
            case Insn::FCMOV_ST: return x64::toString<Cond, ST>(*this, "fcmov");
            case Insn::FNSTCW_M16: return x64::toString<M16>(*this, "fnstcw");
            case Insn::FLDCW_M16: return x64::toString<M16>(*this, "fldcw");
            case Insn::FNSTSW_R16: return x64::toString<R16>(*this, "fnstsw");
            case Insn::FNSTSW_M16: return x64::toString<M16>(*this, "fnstsw");
            case Insn::FNSTENV_M224: return x64::toString<M224>(*this, "fnstenv");
            case Insn::FLDENV_M224: return x64::toString<M224>(*this, "fldenv");
            case Insn::MOVSS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "movss");
            case Insn::MOVSS_M32_RSSE: return x64::toString<M32, RSSE>(*this, "movss");
            case Insn::MOVSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "movsd");
            case Insn::MOVSD_M64_RSSE: return x64::toString<M64, RSSE>(*this, "movsd");
            case Insn::ADDSS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "addss");
            case Insn::ADDSS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "addss");
            case Insn::ADDSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "addsd");
            case Insn::ADDSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "addsd");
            case Insn::SUBSS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "subss");
            case Insn::SUBSS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "subss");
            case Insn::SUBSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "subsd");
            case Insn::SUBSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "subsd");
            case Insn::MULSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "mulsd");
            case Insn::MULSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "mulsd");
            case Insn::DIVSS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "divss");
            case Insn::DIVSS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "divss");
            case Insn::DIVSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "divsd");
            case Insn::DIVSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "divsd");
            case Insn::COMISS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "comiss");
            case Insn::COMISS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "comiss");
            case Insn::COMISD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "comisd");
            case Insn::COMISD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "comisd");
            case Insn::UCOMISS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "ucomiss");
            case Insn::UCOMISS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "ucomiss");
            case Insn::UCOMISD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "ucomisd");
            case Insn::UCOMISD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "ucomisd");
            case Insn::MAXSS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "maxss");
            case Insn::MAXSS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "maxss");
            case Insn::MAXSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "maxsd");
            case Insn::MAXSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "maxsd");
            case Insn::MINSS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "minss");
            case Insn::MINSS_RSSE_M32: return x64::toString<RSSE, M32>(*this, "minss");
            case Insn::MINSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "minsd");
            case Insn::MINSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "minsd");
            case Insn::CMPSD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "cmpsd");
            case Insn::CMPSD_RSSE_M64: return x64::toString<RSSE, M64>(*this, "cmpsd");
            case Insn::CVTSI2SS_RSSE_RM32: return x64::toString<RSSE, RM32>(*this, "cvtsi2ss");
            case Insn::CVTSI2SS_RSSE_RM64: return x64::toString<RSSE, RM64>(*this, "cvtsi2ss");
            case Insn::CVTSI2SD_RSSE_RM32: return x64::toString<RSSE, RM32>(*this, "cvtsi2sd");
            case Insn::CVTSI2SD_RSSE_RM64: return x64::toString<RSSE, RM64>(*this, "cvtsi2sd");
            case Insn::CVTSS2SD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "cvtss2sd");
            case Insn::CVTSS2SD_RSSE_M32: return x64::toString<RSSE, M32>(*this, "cvtss2sd");
            case Insn::CVTTSD2SI_R32_RSSE: return x64::toString<R32, RSSE>(*this, "cvttsd2si");
            case Insn::CVTTSD2SI_R32_M64: return x64::toString<R32, M64>(*this, "cvttsd2si");
            case Insn::CVTTSD2SI_R64_RSSE: return x64::toString<R64, RSSE>(*this, "cvttsd2si");
            case Insn::CVTTSD2SI_R64_M64: return x64::toString<R64, M64>(*this, "cvttsd2si");
            case Insn::PAND_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pand");
            case Insn::PANDN_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pandn");
            case Insn::POR_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "por");
            case Insn::ANDPD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "andpd");
            case Insn::ANDNPD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "andnpd");
            case Insn::ORPD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "orpd");
            case Insn::XORPD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "xorpd");
            case Insn::SHUFPD_RSSE_RMSSE_IMM: return x64::toString<RSSE, RMSSE, Imm>(*this, "shufpd");
            case Insn::MOVLPS_RSSE_M64: return x64::toString<RSSE, M64>(*this, "movlps");
            case Insn::MOVHPS_RSSE_M64: return x64::toString<RSSE, M64>(*this, "movhps");
            case Insn::MOVHLPS_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "movhlps");
            case Insn::PUNPCKLBW_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpcklbw");
            case Insn::PUNPCKLWD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpcklwd");
            case Insn::PUNPCKLDQ_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpckldq");
            case Insn::PUNPCKLQDQ_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpcklqdq");
            case Insn::PUNPCKHBW_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpckhbw");
            case Insn::PUNPCKHWD_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpckhwd");
            case Insn::PUNPCKHDQ_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpckhdq");
            case Insn::PUNPCKHQDQ_RSSE_RSSE: return x64::toString<RSSE, RSSE>(*this, "punpckhqdq");
            case Insn::PSHUFB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pshufb");
            case Insn::PSHUFD_RSSE_RMSSE_IMM: return x64::toString<RSSE, RMSSE, Imm>(*this, "sshufd");
            case Insn::PCMPEQB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpeqb");
            case Insn::PCMPEQW_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpeqw");
            case Insn::PCMPEQD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpeqd");
            case Insn::PCMPEQQ_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpeqq");
            case Insn::PCMPGTB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpgtb");
            case Insn::PCMPGTW_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpgtw");
            case Insn::PCMPGTD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpgtd");
            case Insn::PCMPGTQ_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pcmpgtq");
            case Insn::PMOVMSKB_R32_RSSE: return x64::toString<R32, RSSE>(*this, "pmovmskb");
            case Insn::PADDB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "paddb");
            case Insn::PADDW_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "paddw");
            case Insn::PADDD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "paddd");
            case Insn::PADDQ_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "paddq");
            case Insn::PSUBB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "psubb");
            case Insn::PSUBW_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "psubw");
            case Insn::PSUBD_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "psubd");
            case Insn::PSUBQ_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "psubq");
            case Insn::PMAXUB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pmaxub");
            case Insn::PMINUB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "pminub");
            case Insn::PTEST_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "ptest");
            case Insn::PSLLW_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "psllw");
            case Insn::PSLLD_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "pslld");
            case Insn::PSLLQ_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "psllq");
            case Insn::PSRLW_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "psrlw");
            case Insn::PSRLD_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "psrld");
            case Insn::PSRLQ_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "psrlq");
            case Insn::PSLLDQ_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "pslldq");
            case Insn::PSRLDQ_RSSE_IMM: return x64::toString<RSSE, Imm>(*this, "psrldq");
            case Insn::PCMPISTRI_RSSE_RMSSE_IMM: return x64::toString<RSSE, RMSSE, Imm>(*this, "pcmpistri");
            case Insn::PACKUSWB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "packuswb");
            case Insn::PACKUSDW_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "packusdw");
            case Insn::PACKSSWB_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "packsswb");
            case Insn::PACKSSDW_RSSE_RMSSE: return x64::toString<RSSE, RMSSE>(*this, "packssdw");
            case Insn::RDTSC: return x64::toString(*this, "rdtsc");
            case Insn::CPUID: return x64::toString(*this, "cpuid");
            case Insn::XGETBV: return x64::toString(*this, "xgetbv");
            case Insn::FXSAVE_M64: return x64::toString<M64>(*this, "fxsave");
            case Insn::FXRSTOR_M64: return x64::toString<M64>(*this, "fxrstor");
            case Insn::FWAIT: return x64::toString(*this, "fwait");
            case Insn::RDPKRU: return x64::toString(*this, "rdpkru");
            case Insn::WRPKRU: return x64::toString(*this, "wrpkru");
        }
        assert(false);
        return "unreachable";
    }

    bool X64Instruction::isCall() const { return false; }
    bool X64Instruction::isSSE() const { return false; }
    bool X64Instruction::isX87() const { return false; }

}